# Generated by Django 2.1.7 on 2019-02-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_rsvp_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default_event_img.jpg', upload_to='event_pics'),
        ),
    ]
