# Generated by Django 2.1.7 on 2019-02-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190220_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default_event_img.jpg', upload_to='event_pics', verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rsvp_goal',
            field=models.IntegerField(verbose_name='Attendees Goal'),
        ),
    ]
