# Generated by Django 2.1.7 on 2019-02-20 16:15

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=timezone.now),
        ),
    ]