# Generated by Django 2.1.7 on 2019-02-25 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventannouncement',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
