# Generated by Django 2.1.7 on 2019-02-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20190225_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Space Needle, Seattle WA', max_length=500),
            preserve_default=False,
        ),
    ]
