# Generated by Django 2.1.7 on 2019-02-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=47.6205),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=122.3493),
        ),
    ]
