# Generated by Django 2.1.7 on 2019-02-28 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0016_auto_20190228_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checked_in',
            field=models.ManyToManyField(related_name='events_attended', to=settings.AUTH_USER_MODEL),
        ),
    ]
