# Generated by Django 2.1.7 on 2019-05-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='continuous_charge_miles_needed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_level',
            field=models.CharField(default='Beginner', max_length=200),
        ),
    ]
